board = [["Black", "Rook", "b_rook.png", 0, 0, "life", True],
                      ["Black", "Knight", "b_knight.png", 1, 0, "life"],
                      ["Black", "Bishop", "b_bishop.png", 2, 0, "life"],
                      ["Black", "Queen", "b_queen.png", 3, 0, "life"],
                      ["Black", "King", "b_king.png", 4, 0, "life", True],
                      ["Black", "Bishop", "b_bishop.png", 5, 0, "life"],
                      ["Black", "Knight", "b_knight.png", 6, 0, "life"],
                      ["Black", "Rook", "b_rook.png", 7, 0, "life", True],

                      ["Black", "Pawn", "b_pawn.png", 0, 1, "life"],
                      ["Black", "Pawn", "b_pawn.png", 1, 1, "life"],
                      ["Black", "Pawn", "b_pawn.png", 2, 1, "life"],
                      ["Black", "Pawn", "b_pawn.png", 3, 1, "life"],
                      ["Black", "Pawn", "b_pawn.png", 4, 1, "life"],
                      ["Black", "Pawn", "b_pawn.png", 5, 1, "life"],
                      ["Black", "Pawn", "b_pawn.png", 6, 1, "life"],
                      ["Black", "Pawn", "b_pawn.png", 7, 1, "life"],

                      ["Null", "Null", "noPicture", 0, 2, "dead"], ["Null", "Null", "noPicture", 1, 2, "dead"],
                      ["Null", "Null", "noPicture", 2, 2, "dead"], ["Null", "Null", "noPicture", 3, 2, "dead"],
                      ["Null", "Null", "noPicture", 4, 2, "dead"], ["Null", "Null", "noPicture", 5, 2, "dead"],
                      ["Null", "Null", "noPicture", 6, 2, "dead"], ["Null", "Null", "noPicture", 7, 2, "dead"],

                      ["Null", "Null", "noPicture", 0, 3, "dead"], ["Null", "Null", "noPicture", 1, 3, "dead"],
                      ["Null", "Null", "noPicture", 2, 3, "dead"], ["Null", "Null", "noPicture", 3, 3, "dead"],
                      ["Null", "Null", "noPicture", 4, 3, "dead"], ["Null", "Null", "noPicture", 5, 3, "dead"],
                      ["Null", "Null", "noPicture", 6, 3, "dead"], ["Null", "Null", "noPicture", 7, 3, "dead"],

                      ["Null", "Null", "noPicture", 0, 4, "dead"], ["Null", "Null", "noPicture", 1, 4, "dead"],
                      ["Null", "Null", "noPicture", 2, 4, "dead"], ["Null", "Null", "noPicture", 3, 4, "dead"],
                      ["Null", "Null", "noPicture", 4, 4, "dead"], ["Null", "Null", "noPicture", 5, 4, "dead"],
                      ["Null", "Null", "noPicture", 6, 4, "dead"], ["Null", "Null", "noPicture", 7, 4, "dead"],

                      ["Null", "Null", "noPicture", 0, 5, "dead"], ["Null", "Null", "noPicture", 1, 5, "dead"],
                      ["Null", "Null", "noPicture", 2, 5, "dead"], ["Null", "Null", "noPicture", 3, 5, "dead"],
                      ["Null", "Null", "noPicture", 4, 5, "dead"], ["Null", "Null", "noPicture", 5, 5, "dead"],
                      ["Null", "Null", "noPicture", 6, 5, "dead"], ["Null", "Null", "noPicture", 7, 5, "dead"],

                      ["White", "Pawn", "w_pawn.png", 0, 6, "life"],
                      ["White", "Pawn", "w_pawn.png", 1, 6, "life"],
                      ["White", "Pawn", "w_pawn.png", 2, 6, "life"],
                      ["White", "Pawn", "w_pawn.png", 3, 6, "life"],
                      ["White", "Pawn", "w_pawn.png", 4, 6, "life"],
                      ["White", "Pawn", "w_pawn.png", 5, 6, "life"],
                      ["White", "Pawn", "w_pawn.png", 6, 6, "life"],
                      ["White", "Pawn", "w_pawn.png", 7, 6, "life"],

                      ["White", "Rook", "w_rook.png", 0, 7, "life", True],
                      ["White", "Knight", "w_knight.png", 1, 7, "life"],
                      ["White", "Bishop", "w_bishop.png", 2, 7, "life"],
                      ["White", "Queen", "w_queen.png", 3, 7, "life"],
                      ["White", "King", "w_king.png", 4, 7, "life", True],
                      ["White", "Bishop", "w_bishop.png", 5, 7, "life"],
                      ["White", "Knight", "w_knight.png", 6, 7, "life"],
                      ["White", "Rook", "w_rook.png", 7, 7, "life", True]]